version: "3.8"
services:
  web:
    build: ./app
    image: 305538495820.dkr.ecr.us-east-2.amazonaws.com/workshop2:workshop2_web
    command: gunicorn nc_tutorials.wsgi:application --bind 0.0.0.0:8001
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/usr/src/app/static
    expose:
      - 8001
    environment:
      - DB_NAME=nc_tutorials_db
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_HOST=nctutorials.cgg6swzuvofc.us-east-2.rds.amazonaws.com
      - DB_PORT=5432
      - DATABASE=postgres
      - VIRTUAL_HOST=ec2-3-130-88-126.us-east-2.compute.amazonaws.com
      - VIRTUAL_PORT=8001
  nginx:
    build: ./nginx
    image: 305538495820.dkr.ecr.us-east-2.amazonaws.com/workshop2:workshop2_nginx
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - 8001:80
    depends_on:
      - web
volumes:
  static_volume: